Repository marcdroger/blok-tech-team, pull requests merged in 2022-06, with the labels that each got.

#24 routes aangemaakt voor account en overview
  controller/mainController.js
  views/account.pug
  views/overview.pug
Labels: development

#30 404 pagina gemaakt met pug
  public/css/layout/404.css
  public/css/main.css
  public/img/404.svg
  views/404.pug
Labels: help wanted, development

#38 36 fix mongoose double npm package
  controller/schema/student.js
  package-lock.json
  package.json
Labels: bug

#40 render student data in input field
  views/account.pug
Labels: development

#43 32 intro pagina css
  public/css/layout/userSelect.css
  public/css/main.css
  views/index.pug
Labels: development

#45 Overview page cards
  controller/mainController.js
  public/css/layout/404.css
  public/css/layout/matches.css
  public/css/layout/nav.css
  public/css/main.css
  views/404.pug
  views/layout/matches.pug
  views/layout/nav.pug
  views/matches.pug
  views/overview.pug
Labels: development

#54 Land input gewijzigd naar dropdown
  public/css/layout/account.css
  views/account.pug
Labels: design, development

#67 Validator toegevoegd + select + sub tekst
  controller/mainController.js
  package-lock.json
  package.json
  views/account.pug
  views/add.pug
Labels: bug, help wanted, development

#68 27 readme aanvullen: devdependencies
  README.md
Labels: documentation

#70 Uglify
  gulpfile.js
  package-lock.json
  package.json
  public/script/main.js
  scripts/main.js
Labels: development

#65 Dependency security issue
  package-lock.json
  package.json
Labels: development

#77 Sessions
  controller/mainController.js
  controller/modules/updateStudent.js
  index.js
  package-lock.json
  package.json
  public/css/style.css
  sass/layout/_account.scss
  sass/layout/_userselect.scss
  views/index.pug
Labels: development

#73 Hide nav index
  controller/mainController.js
  package.json
  views/layout/template.pug
Labels: bug

#82 Validator gefixt
  controller/mainController.js
  public/css/style.css
  sass/layout/_message.scss
  sass/style.scss
  sass/variables/_colors.scss
  views/account.pug
  views/add.pug
Labels: design, development

#83 Matching
  controller/mainController.js
  package-lock.json
  views/matches.pug
Labels: development

#86 Email en add user gewijzigd
  public/css/style.css
  sass/layout/_index.scss
  sass/layout/_main.scss
  sass/layout/_matches.scss
  sass/style.scss
  views/index.pug
  views/matches.pug
Labels: design, development, usability
